#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("play.billing.v3.Resource", IsApplication=true)]

namespace play.billing.v3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int CancelButton = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int ConsumeButton = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int InventoryButton = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int PurchaseButton = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int SkuButton = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int UnavailableButton = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int ApplicationName = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int Cancel = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int Consume = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Purchase = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int Purchases = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int Sku = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int Unavailable = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
